<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RequirementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();

        DB::table('requirements')->insert([

            //LICENCIA DE CONSTRUCCIÓN MENOR A 45M2
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 1,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 1,
            ],
            [
                "nombre" => "Croquis de realización de trabajos o proyecto.",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 1,
            ],
            [
                "nombre" => "Fotografías del lugar de la construcción, de la construcción o fachada sea el caso.",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 1,
            ],
            [
                "nombre" => "Fotografías del lugar de la construcción, de la construcción o fachada sea el caso.",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 1,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 1,
            ],
            //LICENCIA DE CONSTRUCCIÓN (MAYOR A 45M2)
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "NÚMERO OFICIAL",
                "descripcion" => "Oficinas, comercio, salud, recreación, deporte, alojamiento, seguridad, educación, servicios, industrial e infraestructura",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA",
                "descripcion" => "Hoteles, comercios, oficinas, escuelas, hospitales, centros de reunión, salas de espectaculos, clubes deportivos, sociales, baños, templos y estacionamientos) indicando las condicionantes que en ella se requieran para la ocupación del predio con el uso propuesto.",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 2,
            ],
            [
                "nombre" => "Bitácora de la construcción",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 2,
            ],

            //LICENCIA PROYECTOS ESPECIALES
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Alineamiento y numero oficial",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Apeo y Deslinde catastral",
                "descripcion" => null,
                "nota" => "Por parte de la Dirección de Catastro",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Factibilidad de la dotacion de los servicios.",
                "descripcion" => "Energia electrica, agua potable y alcantarillado",
                "nota" => "Expedidas por  las dependencias y organismos responsables",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Certificación de Alineamiento y aprobación del proyecto de accesos.",
                "descripcion" => "Por parte de la S.C.T.",
                "nota" => "En caso de colindar con vias federales",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Resolución positiva de la Manifestacion del impacto ambiental.",
                "descripcion" => "Por parte del IEMAZ",
                "nota" => "Para estaciones de servicio",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Aprobacion del Plan de contingencias y visto bueno de Operación.",
                "descripcion" => "Por parte de la Delalegacion de protección civil estatal y municipal",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Acta constitutiva.",
                "descripcion" => "De la empresa",
                "nota" => "En su caso.",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Estudio de Mecanica de suelos",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Dictamen de Impacto Urbano y Vial.",
                "descripcion" => null,
                "nota" => "Otorgado por el organo estatal en materia de desarrollo urbano (SEDUVOT)",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],
            [
                "nombre" => "Constancia de compatibilidad urbánistica estatal y municipal",
                "descripcion" => null,
                "nota" => "Así como las condicionantes marcadas en ellas para este tramite",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 3,
            ],

            //PERMISO PARA BARDEO
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 4,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 4,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 4,
            ],
            //PERMISO DE ENJARRES, APLANADOS, FIRMES, COLOCACIÓN DE PISO, YESO, PETATILLO, TABLARROCA, CANCELERIA, ENMALLADO
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 5,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 5,
            ],
            //PRÓRROGA O EXTENSIÓN DEL TIEMPO DE CONSTRUCCIÓN
            [
                "nombre" => "Licencia que se le otorgó.",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 6,
            ],
            //NÚMERO OFICIAL Y ALINEAMIENTO
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 7,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 7,
            ],
            [
                "nombre" => "Fotografías de la propiedad",
                "descripcion" => "Del frente y de costado",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 7,
            ],

            //PERMISO PARA INSTALACIÓN DE TORRE EÓLICA
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 8,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA",
                "descripcion" => "Hoteles, comercios, oficinas, escuelas, hospitales, centros de reunión, salas de espectaculos, clubes deportivos, sociales, baños, templos y estacionamientos) indicando las condicionantes que en ella se requieran para la ocupación del predio con el uso propuesto.",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 8,
            ],

            //PERMISO PARA INSTALACIÓN DE ANTENA DE TELECOMUNICACIÓN
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 9,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA",
                "descripcion" => "Hoteles, comercios, oficinas, escuelas, hospitales, centros de reunión, salas de espectaculos, clubes deportivos, sociales, baños, templos y estacionamientos) indicando las condicionantes que en ella se requieran para la ocupación del predio con el uso propuesto.",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 9,
            ],

            //PERMISO PARA ESTACIÓN DE SERVICIO GAS L.P. PARA CARBURACIÓN
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Alineamiento y numero oficial",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Apeo y Deslinde catastral",
                "descripcion" => null,
                "nota" => "Por parte de la Dirección de Catastro",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Factibilidad de la dotacion de los servicios.",
                "descripcion" => "Energia electrica, agua potable y alcantarillado",
                "nota" => "Expedidas por  las dependencias y organismos responsables",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Certificación de Alineamiento y aprobación del proyecto de accesos.",
                "descripcion" => "Por parte de la S.C.T.",
                "nota" => "En caso de colindar con vias federales",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Permiso para la distribución de Gas L.P. para carburacion.",
                "descripcion" => "Por parte de ASEA,",
                "nota" => "Así como la aprobacion del proyecto, con planos sellados y firmados",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Resolución positiva de la Manifestacion del impacto ambiental.",
                "descripcion" => "Por parte del IEMAZ",
                "nota" => "Para estaciones de servicio",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Aprobacion del Plan de contingencias y visto bueno de Operación.",
                "descripcion" => "Por parte de la Delalegacion de protección civil estatal y municipal",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Acta constitutiva.",
                "descripcion" => "De la empresa",
                "nota" => "En su caso.",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Estudio de Mecanica de suelos",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "Dictamen de Impacto Urbano y Vial.",
                "descripcion" => null,
                "nota" => "Otorgado por el organo estatal en materia de desarrollo urbano (SEDUVOT)",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 10,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA",
                "descripcion" => "Hoteles, comercios, oficinas, escuelas, hospitales, centros de reunión, salas de espectaculos, clubes deportivos, sociales, baños, templos y estacionamientos) indicando las condicionantes que en ella se requieran para la ocupación del predio con el uso propuesto.",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 10,
            ],

            //PERMISO PARA ESTACIÓN DE SERVICIO (GASOLINERA)
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Autorizaciones.",
                "descripcion" => "Por parte de Junta de Protección y conservación de monumentos y el visto bueno de  la adminsitración del centro histórico del ayuntamiento de Zacatecas",
                "nota" => 'De encontrarse dentro del polígono de protección y conservación',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Alineamiento y numero oficial",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Apeo y Deslinde catastral",
                "descripcion" => null,
                "nota" => "Por parte de la Dirección de Catastro",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Factibilidad de la dotacion de los servicios.",
                "descripcion" => "Energia electrica, agua potable y alcantarillado",
                "nota" => "Expedidas por  las dependencias y organismos responsables",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Certificación de Alineamiento y aprobación del proyecto de accesos.",
                "descripcion" => "Por parte de la S.C.T.",
                "nota" => "En caso de colindar con vias federales",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Permiso para la distribución de Gas L.P. para carburacion.",
                "descripcion" => "Por parte de ASEA,",
                "nota" => "Así como la aprobacion del proyecto, con planos sellados y firmados",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Resolución positiva de la Manifestacion del impacto ambiental.",
                "descripcion" => "Por parte del IEMAZ",
                "nota" => "Para estaciones de servicio",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Aprobacion del Plan de contingencias y visto bueno de Operación.",
                "descripcion" => "Por parte de la Delalegacion de protección civil estatal y municipal",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Acta constitutiva.",
                "descripcion" => "De la empresa",
                "nota" => "En su caso.",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Planos arquitectónicos",
                "descripcion" => "Fachadas, cortes, detalles, especificaciones, ejes, acotaciones escalas y cuadro de datos indicando la superficie de construcción por planta",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Planos eléctricos",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones.",
                "nota" => 'Firma de Director Responsable de Obra (DRO), Firma de corresponsable de obra en instalaciones en construcciones no habitacionales, especiales  de más de 300 m2 o con carga elétrica instalada mayor de quince kilowatts',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Planos sanitarios",
                "descripcion" => "Instalaciones en planta, detalles, especificaciones de materiales, simbologia y cuadro de datos.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Planos estructurales",
                "descripcion" => "Planta de cimentación, especificación de losas, trabes, cadenas, columnas y muros de cargas en planta; '\n'Detalles de losa, trabes, cadenas, columnas; '\n'especificaciones de materiales, simbologia, notas generales y cadro de datos. '\n'Firmado por quien realizó la memoria de cálculo",
                "nota" => 'Firmado por quien realizó la memoria de cálculo',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Estudio de Mecanica de suelos",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "Dictamen de Impacto Urbano y Vial.",
                "descripcion" => null,
                "nota" => "Otorgado por el organo estatal en materia de desarrollo urbano (SEDUVOT)",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 11,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA",
                "descripcion" => "Hoteles, comercios, oficinas, escuelas, hospitales, centros de reunión, salas de espectaculos, clubes deportivos, sociales, baños, templos y estacionamientos) indicando las condicionantes que en ella se requieran para la ocupación del predio con el uso propuesto.",
                "nota" => 'Para construcciones mayores a 300 m2 o construcciones no habitacionales.',
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 11,
            ],

            //CONSTANCIA DE SERVICIOS URBANOS
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 12,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 12,
            ],

            //CONSTANCIA DE AUTOCONSTRUCCIÓN Y VARIAS
            [
                "nombre" => "Licencia de Construcción",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 13,
            ],
            [
                "nombre" => "Credencial de Elector de los trabajadores que intervienen en la construcción",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 13,
            ],

            //CONSTANCIA DE SEGURIDAD ESTRUCTURAL
            [
                "nombre" => "Dictamen emitido por un Director Responsable de Obra (DRO)",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 14,
            ],

            //REGULARIZACIÓN
            //?id 15

            //CONSTANCIA COMPATIBILIDAD URBANÍSTICA
            [
                "nombre" => "Documento que legalmente ampare la propiedad del predio",
                "descripcion" => "Predial vigente si es propio y contrato de arrendamiento si es rentado",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 16,
            ],
            [
                "nombre" => "Identificación del solicitante",
                "descripcion" => null,
                "nota" => "En caso de ser persona moral, el acta constitutiva y el poder del representante legal y su identificación",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 16,
            ],
            [
                "nombre" => "Firmas y VoBo de lo vecinos de la zona",
                "descripcion" => null,
                "nota" => "Giros o establecimientos que por sus características pudieran ocasionar alguna problemática con los vecinos",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 16,
            ],
            [
                "nombre" => "CONSTANCIA DE COMPATIBILIDAD URBANÍSTICA ESTATAL",
                "descripcion" => "Fraccionamientos.",
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 16,
            ],

            //ANUNCIOS ADOSADOS A FACHADA
            [
                "nombre" => "Fotografía a color de la fachada",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Fotografía a color panorámica",
                "descripcion" => "Donde salgan las colondancias del sitio",
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Dictamen emitido por el departamento de Planeación y Desarrollo Urbano",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Dictamen de Protección Civil",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Contrato de arrendamiento",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 17,
            ],
            [
                "nombre" => "Dictamen de vo.bo. Aprobado por el INAH ",
                "descripcion" => '“Zona Típica” establecida en el artículo 9 de la Ley de Protección y Conservación de Monumentos y Zonas Típicas de Zacatecas',
                "nota" => "En caso de encontrarse en Centro Histórico",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 17,
            ],

            //ANUNCIOS TIPO ESTRUCTURALES
            [
                "nombre" => "Fotografía a color de la fachada",
                "descripcion" => "Fraccionamientos.",
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Fotografía a color panorámica",
                "descripcion" => "Donde salgan las colondancias del sitio",
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Dictamen emitido por el departamento de Planeación y Desarrollo Urbano",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Dictamen de Protección Civil",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Dictamen de Impacto Urbano y Vial.",
                "descripcion" => null,
                "nota" => "Otorgado por el organo estatal en materia de desarrollo urbano (SEDUVOT)",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Memoria de cálculo",
                "descripcion" => "Firmada por calculista con número de cédula profesional.",
                "nota" => 'Firma de Director Responsable de Obra (DRO)',
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Contrato de arrendamiento",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 18,
            ],
            [
                "nombre" => "Dictamen de vo.bo. Aprobado por el INAH ",
                "descripcion" => '“Zona Típica” establecida en el artículo 9 de la Ley de Protección y Conservación de Monumentos y Zonas Típicas de Zacatecas',
                "nota" => "En caso de encontrarse en Centro Histórico",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 18,
            ],

            //ANUNCIOS TEMPORALES ADOSADOS
            [
                "nombre" => "Fotografía a color panorámica",
                "descripcion" => "Donde salgan las colondancias del sitio",
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 19,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 19,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 19,
            ],
            [
                "nombre" => "Permiso del dueño del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 19,
            ],
            [
                "nombre" => "Período de colocación",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 19,
            ],
            [
                "nombre" => "Dictamen de vo.bo. Aprobado por el INAH ",
                "descripcion" => '“Zona Típica” establecida en el artículo 9 de la Ley de Protección y Conservación de Monumentos y Zonas Típicas de Zacatecas',
                "nota" => "En caso de encontrarse en Centro Histórico",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 19,
            ],

            //ANUNCIOS EN VEHÍCULOS
            [
                "nombre" => "Tarjeta de circulaciónd el vehículo",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 20,
            ],
            [
                "nombre" => "Visto Bueno de la Dirección de Transporte, Tránsito y Vialidad del Estado de Zacatecas",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 20,
            ],
            [
                "nombre" => "Visto Bueno de Impacto Ambiental emitido por el Departamento de Medio Abiente y Ecología, de Presidencia Municipal de Zactecas.",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 20,
            ],

            //SEGURIDAD DE ESTRUCTURA ANTENAS
            //?id 21

            //AUTORIZACIÓN DE SUBDIVISIÓN, DESMEMBRACIÓN O FUSIÓN DE TERRENOS URBANOS
            [
                "nombre" => "Escritura o título de la propiedad a subdividirescritura o título de la propiedad a subdividir",
                "descripcion" => "Debidamente inscritas en el Registro Público de la Propiedad.",
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Certificado actualizado de libertad de gravamen.",
                "descripcion" => "Se solicita en el Registro Público de la Propiedad",
                "nota" => "Tiene vigencia de 30 días",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Recibo de pago del predial del año fiscal correspondiente",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Credencial de elector.",
                "descripcion" => null,
                "nota" => "Del solicitante",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Carta poder.",
                "descripcion" => "Formato simple",
                "nota" => "En su caso",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Plano general de las fracciones a subdividir y planos individuales.",
                "descripcion" => "Acotados y con superficie de cada fracción.",
                "nota" => "Planos GEORREFERENCIADOS con coordenadas UTM",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Plano general de las fracciones a subdividir y planos individuales.",
                "descripcion" => "Acotados y con superficie de cada fracción.",
                "nota" => "Planos GEORREFERENCIADOS con coordenadas UTM",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => true,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Factibilidad de la dotacion de los servicios.",
                "descripcion" => "Energia electrica, agua potable y alcantarillado",
                "nota" => "Expedidas por  las dependencias y organismos responsables",
                "activo" => true,
                "obligatorio" => true,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Fotografía del predio",
                "descripcion" => null,
                "nota" => null,
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
            [
                "nombre" => "Diligencias judiciales o administrativas de apeo y deslinde y de posesión del predio (sic art. 235 del Código Territorial y Urbano para el Estado de Zacatecas y sus Municipios y demás artículos que se consideren inherentes del mismo código vigente).",
                "descripcion" => "De conformidad al art. 191 del Reglamento Orgánico del Municipio de Zacatecas",
                "nota" => "Cuando el Presidente Municipal, por conducto del Secretario de Desarrollo Urbano y Medio Ambiente, lo considere necesario",
                "activo" => true,
                "obligatorio" => false,
                "es_plano" => false,
                "license_type_id" => 22,
            ],
        ]);
    }
}
